name: web-tools_static-deploy
run-name: Web tools 정적 페이지 배포

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '배포할 브랜치 입력'
        required: true
        default: 'develop'
        type: string

jobs:
  deploy-ui:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: 선택한 브랜치 표시
        run: |
          echo "배포할 브랜치: ${{ github.event.inputs.branch }}"

      - name: node 설치
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: pnpm 설치
        uses: pnpm/action-setup@v4

      - name: 의존성 설치
        run: pnpm install

      - name: 의존하는 패키지 빌드
        run: pnpm build --filter=@repo/ui

      - name: 빌드
        run: pnpm build --filter=web-tools

      - name: AWS 인증 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3에 빌드된 파일 업로드
        env:
          BUCKET_NAME: ${{ vars.BUCKET_NAME }}
        run: |
          cd ./packages/web-tools
          aws s3 sync --region ap-northeast-2 ./dist s3://$BUCKET_NAME/web-tools-static --delete

      - name: CloudFront 캐시 무효화
        env:
          CLOUD_FRONT_ID: ${{ vars.WEB_TOOLS__CLOUD_FRONT_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUD_FRONT_ID --paths "/*"
